{
  "hash": "fac19ef755801654dc2b4130f4ec3c0f",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"收敛：decoder-only、MoE 与开源运动\"\n---\n\n卷二收官。2019 年的时候，做 NLP 要在 GPT 与 BERT 之间站队、在十种注意力和四种训练目标里挑花活；到 2023 年，新发布的基座模型几乎清一色长成同一个样子：**decoder-only Transformer、下一词预测、几十层、几千亿参数**。架构的多样性塌缩成了共识模板——本章盘点这场收敛的三股推力（decoder-only 的经济学、稀疏化对\"参数与算力解耦\"的回答、开源运动对\"谁能拥有模型\"的回答），做一次 MoE 的最小实验，然后合上卷二。\n\n::: {.callout-tip title=\"算力需求\"}\n**A 级**：笔记本 CPU · MoE 对照实验约 2 分钟。\n:::\n\n::: {.callout-era title=\"时代快照 · 2022–2024\"}\n- **算力**：万卡集群成为旗舰训练的门槛；MoE（千级专家）成为\"参数上量、算力不炸\"的主路（GShard/Switch/后来的 Mixtral）；\n- **数据**：Chinchilla 配方生效后，数据工程（清洗、去重、配比）成为模型竞争力的大头；\n- **认知**：\"基础模型\"（foundation model）一词（2021）被广泛接受——范式收敛伴随 vocabulary 的收敛；\n- **关键事实**：2023 年 2 月 LLaMA 权重泄露、7 月 Meta 干脆正式开源——开源社区的微调生态（Alpaca 一族）在几个月内把\"小模型 + 好数据\"的路线跑通。**闭源壁垒被证明比想象中薄**。\n:::\n\n## 本章问题\n\n1. 收敛到 decoder-only 的三条理由，各自站不站得住？（5.4 伏笔的正式结算）\n2. MoE 如何解耦\"参数量\"与\"每 token 算力\"？代价是什么？（最小实验 + 诚实结果）\n3. 这场收敛**排除**了什么——被收敛掉的多样性，损失在哪里？\n\n## 历史中的尝试（包括弯路）\n\n**decoder-only 的三张牌**：①**信号密度**——每个 token 都产生监督（5.4 的验货结论）；②**scaling 友好**——目标单一、损失稳定、幂律好测（6.1 的曲线全部画在这条目标上）；③**工程极简**——训练即推理的彩排、KV 缓存直接可用、流水线好切。 encoder-decoder（T5 一系）与 MLM 路线没有输在\"双向无用\"，输在**规模化时代的适配性**。\n\n**MoE 的谱系**：思想源头是 1991 年的混合专家（Jacobs et al.——古老的联想，与 LSTM 同年出生）；2017 年后与 Transformer 结合成稀疏层（Shazeer 的 Sparsely-Gated MoE、Google 的 Switch Transformer 每层几千专家、2023 年 Mistral 的 Mixtral 8×7B 开源爆款）。**\"参数存知识、算力做计算\"的解耦**让千亿级参数以百亿级的单 token 成本运行。\n\n**弯路：MoE 的训练之难**。负载不均（几个专家被挤爆、其余闲置）、训练不稳、微调娇气——解药是一整套工程（辅助负载损失、容量因子、z-loss）。**稀疏性的收益从来不是免费的**——本章实验会亲手撞上这一点。\n\n**开源运动**：LLaMA（2023）按 Chinchilla 配方证明\"小而充分训练\"可行 → 泄露与正式开源 → 社区微调生态爆发 → 各家跟进（Mistral、Qwen、DeepSeek 一族）。**研究-工程-社区的三级火箭**取代了\"单实验室闭门造模型\"的旧范式。9.1 会把这段放到 Bitter Lesson 的延长线上复盘。\n\n::: {.callout-research title=\"停一停，你来当研究者\"}\nMoE 实验设计题。手里的零件：`MoEMLP`（2 位专家、top-1 稀疏路由、直通门梯度）。计划：把 d=32 的 MiniGPT 第二块换成 MoE，与 dense 对照。\n\n运行之前写下预测：\n\n1. **参数账**：dense 的 MLP 隐层是 4d；MoE 用 2 位专家、各 2d 隐层——两边的参数量与每 token 的活跃 FLOPs 各是什么关系？\n2. **成绩预测**：同预算下 MoE 会赢、输、还是平？（提示：我们的尺度只有 2.7 万参数、语料 6 万字符——MoE 的理论收益需要什么条件？）\n3. **路由预测**：训练后两位专家的使用率会是 50/50 吗？如果不是，往哪偏、为什么？\n\n写完再运行——第 2 问的诚实答案是本章最有分量的结果。\n:::\n\n## 核心思想\n\n**收敛的三股力**，用账本语言各记一笔：\n\n- **Decoder-only**：在\"信号密度 × scaling 可测性 × 工程简洁\"的三维评分上全面领先——**不是最优的架构，是最可规模化的架构**（Bitter Lesson 的架构版判决）；\n- **MoE**：把\"参数\"与\"每 token 计算\"解耦——知识可以更便宜地**存**，取用时只付路过的那部分算力。代价是训练复杂度与负载均衡的新税；\n- **开源**：把\"基座\"从产品降级为商品——当架构收敛、配方公开（Chinchilla）、数据管道可复制时，**护城河只剩数据、算力与对齐**（后两者正是卷三的主题）。\n\n**收敛的代价**：被收敛掉的还有多样性——encoder 路线在检索/嵌入场景仍是活的传统（5.4 的回声），稀疏注意力、线性复杂度、状态空间模型（4.2 的 RNN 还魂一族）都在等待\"长上下文的账单\"到期后接管（8.x）。**收敛是特定账本下的最优解，账本变了，格局重开**。\n\n## 从零实现\n\n**MoE 对照实验**：dense d=32（第二块 MLP 隐层 4d=128）vs 同模型第二块换成 `MoEMLP`（2 位专家、各 2d=64 隐层）——**总参数相近、每 token 活跃算力减半**：\n\n::: {#78067f0e .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\n\nfrom dlbook.data.corpus import char_corpus, make_grammar_corpus\nfrom dlbook.transformer import MiniGPT\nfrom dlbook.transformer.layers import MoEMLP\nfrom dlbook.utils import set_seed\n\nset_seed(42)\n\narr_t = np.array(char_corpus(make_grammar_corpus(60000, seed=0))[0])\narr_v = np.array(char_corpus(make_grammar_corpus(12000, seed=1))[0])\nV = len(char_corpus(make_grammar_corpus(60000, seed=0))[1])  # 词表取自完整训练文本\nvb = np.stack([arr_v[s : s + 65] for s in np.random.default_rng(7).integers(0, len(arr_v) - 65, size=200)])\n\n\ndef train(model, steps=1500, seed=0):\n    rng = np.random.default_rng(seed)\n    for step in range(steps):\n        lr = 0.15 * min(1.0, (step + 1) / 150) * (1 - 0.9 * step / steps)\n        starts = rng.integers(0, len(arr_t) - 65, size=16)\n        batch = np.stack([arr_t[s : s + 65] for s in starts])\n        model.loss_and_backward(batch)\n        model.step(lr, clip=1.0)\n    return model\n\n\ndense = MiniGPT(V, d_model=32, n_heads=2, n_blocks=2, block_size=64, seed=0)\ntrain(dense)\n\nmoe = MiniGPT(V, d_model=32, n_heads=2, n_blocks=2, block_size=64, seed=0)\nmoe.blocks[1].mlp = MoEMLP(32, n_experts=2, seed=77)\ntrain(moe)\n\nprint(f\"dense: val loss = {dense.loss_on(vb):.3f}\")\nprint(f\"MoE:   val loss = {moe.loss_on(vb):.3f}\")\nprint(f\"专家使用率: {np.round(moe.blocks[1].mlp.usage, 3)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ndense: val loss = 1.909\nMoE:   val loss = 1.938\n专家使用率: [0.741 0.259]\n```\n:::\n:::\n\n\n典型的诚实结果：**MoE 1.94 对 dense 1.91——打平或略输**，且使用率失衡（约 0.74/0.26，没有负载均衡辅助损失的约束）。这不是 MoE 的失败，是**尺度与配方**的证词：\n\n1. **收益需要尺度**：两位专家在 2.7 万参数里分不到足够的专业化空间；真实 MoE 的收益在百亿千亿参数、多领域数据时才兑现（专家按领域/句法分工）；\n2. **负载均衡是生命线**：使用率失衡意味着相当一部分参数在偷懒——Switch Transformer 们靠辅助损失与容量因子驯服它（我们的玩具没装，练习 3 补上）；\n3. **训练税**：稀疏路由的梯度不如 dense 稠密——同预算下略慢是常态。\n\n**玩具的零结果与产业的千亿结果并存**，正是\"账本第二问（数据）与第三问（规模）决定技术适用域\"的又一课——把这句话和 2.3（dropout 在玩具上平庸、在大模型上辉煌）对照：**同一门课，卷一讲过一遍了**。\n\n## 消融实验\n\n**专家数扫描**：把专家从 2 位加到 4 位（每位隐层 d=32，保持总活跃算力近似）——失衡会缓解还是恶化？（预测：专家越多，无约束的均衡越难自发形成——负载均衡损失从\"可选\"变\"必需\"的临界点。）\n\n::: {#bca8f7a3 .cell execution_count=2}\n``` {.python .cell-code}\nmoe4 = MiniGPT(V, d_model=32, n_heads=2, n_blocks=2, block_size=64, seed=0)\nmoe4.blocks[1].mlp = MoEMLP(32, n_experts=4, seed=77)\ntrain(moe4)\nprint(f\"4 专家: val loss = {moe4.loss_on(vb):.3f}, 使用率 = {np.round(moe4.blocks[1].mlp.usage, 3)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n4 专家: val loss = 2.013, 使用率 = [0.645 0.337 0.017 0.   ]\n```\n:::\n:::\n\n\n## 本章 Loss 账本（卷二总账的第一页）\n\n| 问题 | 回答 |\n|---|---|\n| 在优化什么 loss？ | 仍是下一词交叉熵——但 MoE 把\"降它的成本\"拆成两本账：**存知识的参数账**与**取知识的算力账** |\n| 数据从哪来？ | 收敛后的竞争前哨：配比与清洗（本章一笔带过，9.2 展开） |\n| 买到了什么能力？ | 模板化的一切：可复制的训练配方、可外推的曲线、可解耦的成本结构 |\n| 没买到什么？ | **输出分布的可控性**——base model 会续写不会听话；**与人类意图的对齐**——卷三的全部动因 |\n\n::: {.callout-echo title=\"回声\"}\n- MoE 的\"存算解耦\" → 推理经济学的军备库（量化、蒸馏是它的兄弟）；8.x 的 agent 成本核算会再见到这本账；\n- 开源运动 → 权重作为公共品；微调生态（LoRA 一族，7.2）是它的直接产物；\n- 收敛的宿命 → 长上下文账单（8.x）与状态空间模型的还魂——**每一次\"终局\"都埋着下一局**；\n- 卷二主线收束：从 n-gram 的计数到万亿参数的幂律，**\"预测下一词\"从未变过，变的只是把 loss 降得更低的手段**——下一卷问：降好了 loss，然后呢？\n:::\n\n::: {.callout-paper title=\"论文时光机\"}\n**Fedus, W., Zoph, B. & Shazeer, N. (2022).** *Switch transformers: Scaling to trillion parameter models with simple and efficient sparsity.* JMLR.（配对阅读 Touvron et al. 2023 的 LLaMA 论文）\n\n- **读什么**：Switch 的图 2（top-1 路由示意）与第 2 节的负载均衡损失（本章玩具缺失的那味药）；LLaMA 的表 1（\"小模型充分训练\"的战绩表）；\n- **跳过**：分布式系统细节；\n- **历史注**：Shazeer 是 Transformer 八作者之一——2017 年架构论文的核心作者在 2017–2022 年间持续供给稀疏化的关键件（Mesh-TF、Switch、GLU）。**架构收敛不是自然事件，是一小群人持续下注的结果**。开源一线读 LLaMA → Alpaca → Mixtral 的接力，看范式如何在组织间流动。\n:::\n\n## 遗留问题（= 卷三的入场券）\n\n1. base model 是一台强大的续写机器——**为什么它不听话**？让它听话的最小改动是什么？（→ 7.1 base model 的分布、7.2 SFT）；\n2. \"听话\"本身如何变成一个可优化的目标？（→ 7.3 RLHF：把人类偏好写成 loss）；\n3. 当模型的推理能力成为新前线，loss 的故事怎么续写？（→ 7.4 RLVR 与测试时计算）。\n\n## 练习\n\n1. **造轮子**：给 `MoEMLP` 加负载均衡辅助损失（$L_{aux} = E \\sum_e f_e \\cdot p_e$，$f_e$ 为使用率、$p_e$ 为平均门概率），权重 0.01，重训——使用率与 loss 各怎么变？\n2. **预测再运行**：把 MoE 的路由从 top-1 改成 top-2（两位专家输出平均）——loss、使用率、每 token 算力各怎么变？（稠密化是 MoE 稳定性的常见退路。）\n3. **消融**：换一个 seed 重跑 MoE 对照五次，统计胜负——**1.94 vs 1.91 在方差之内吗**？（样本量意识：一切\"打平\"结论都要过这关。）\n4. **论文映射**：用四问账本拆 LLaMA——注意它\"买到\"一栏几乎全是**可复制性与开放性**，闭源论文里这些格子是空的。\n5. **进阶（卷三预习）**：用卷二的任意 base 模型（我们的 MiniGPT）采样 200 个字符，统计其中\"完整英文单词\"的比率与\"重复片段\"的比率——为 7.1 的\"续写怪癖\"观察提前采证。\n\n::: {.callout-note title=\"练习答案\" collapse=\"true\"}\n**练习 1**：使用率趋向均衡（如 0.55/0.45），loss 或微升或微降——均衡与质量是两本账，辅助损失买的是前者的保险；真实系统里没有它，MoE 会退化成\"单专家 + 死权重\"。\n\n**练习 2**：top-2 更稳（梯度更密）但每 token 算力翻倍——**稀疏性的收益被稀释**；实践中 top-1（Switch）与 top-2（Mixtral）各有阵地，是\"稳定性 vs 稀疏度\"的汇率问题。\n\n**练习 5 提示**：典型样本里\"完整词\"过半但\"重复片段\"显著（循环复读是循环网络时代的老病，在弱 base 模型上仍可见）——7.1 会把这类观察系统化为\"分布的怪癖\"，并论证为什么需要后训练。\n:::\n\n",
    "supporting": [
      "part6-convergence_files"
    ],
    "filters": [],
    "includes": {}
  }
}