{
  "hash": "7b701bd05185ae255ceea694a8acd9d8",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Transformer：从补丁到架构\"\n---\n\n2017 年 6 月，八位 Google 的研究者发表了论文，标题只有一个句子：*Attention Is All You Need*（注意力就是你所需要的一切）。宣言的内容是把 5.1 的补丁逻辑推到尽头：**既然注意力已经承担了全部的\"看哪里\"工作，把循环扔掉**。序列的位置信息用位置编码补上，层与层之间用残差与归一化缝合——剩下的全是矩阵乘法。这个架构后来叫 Transformer，它是 GPT 的 T、BERT 的 T、也是今天一切大模型的骨架。本章我们把它从零搭起来——全书代码量的最高点——并看着它在同一条 2.4K 字符的语料上，把此前所有模型甩在身后。\n\n::: {.callout-tip title=\"算力需求\"}\n**B 级边缘**：笔记本 CPU 约 15 秒（仍属 A 级体验；训练单元可自由缩减）。\n:::\n\n::: {.callout-era title=\"时代快照 · 2015–2017\"}\n- **算力**：注意力去掉循环后整条序列的前向可以一次算完（矩阵乘法吃满 GPU）——这是架构对硬件的投名状：Transformer 的成功一半是 NVIDIA 的成功；\n- 数据：WMT 语料继续当燃料；序列建模从此与\"数据并行\"全面兼容；\n- 认知：循环网络被视为序列建模的本质结构（\"序列问题天然需要状态\"），扔掉循环在当时更像异端——论文标题的挑衅语气是有对象的；\n- 关键事实：论文提交到 NeurIPS 2017 时，八位作者里没有一位料到这个架构会在五年后支撑起千亿参数的语言模型——他们解决的是翻译的工程问题（训练慢）。\n:::\n\n## 本章问题\n\n1. 去掉循环后，\"序列的顺序\"从哪来？（位置编码——没有它，注意力看到的是词袋）\n2. 完整的 Transformer 块由哪些部件组成，为什么这样组装？（多头注意力 + 前馈 + 残差 + 归一化——每一件都是老朋友）\n3. 它在同一条语料上比 RNN/LSTM/n-gram 强多少？训练的稳定性从哪来？（梯度裁剪——又是配方）\n\n## 历史中的尝试（包括弯路）\n\n**自注意力的前史**：2016–2017 年间多个团队尝试把注意力用在序列内部（Long et al. 2016 的结构化自注意力、Parikh et al. 2016 的分解）。Vaswani 等人的贡献不是发明注意力，而是极端化：彻底删除循环与卷积，用位置编码补顺序，堆叠残差块——\"少即是多\"的架构设计哲学。\n\n**弯路：并行 RNN 的努力**。另一条路线试图保住循环但并行化（stacked、dilated、bidirectional 的各种组合）——串行依赖始终是硬伤，每一步都要等上一步。有些约束是数学的，不是工程的——认识到这一点的标志，就是放弃在这条路上继续投入。\n\n**多头的设计**：一组注意力只能学一种\"看的方式\"；八组并行（多头），每组在自己的子空间里自由分工——有的看相邻词、有的看句法依存、有的只看分隔符。并行复用同一输入的多个视图，这个思想此后出现在一切多分支设计里。\n\n**训练配方的隐性贡献**：warmup 学习率、梯度裁剪、残差上的 LayerNorm（pre-LN）——原论文的这些\"工程细节\"后来被证明关乎生死（post-LN 在深层会训崩）。架构的光环下永远藏着配方的汗水——2.5 的教训第三次上演。\n\n::: {.callout-research title=\"停一停，你来当研究者\"}\n拼图时间。你已经拥有全部零件：点积注意力（5.1）、残差连接（3.2）、LayerNorm（2.3 的 BN 之亲）、MLP（1.3）、词嵌入（4.4）。在阅读下面的架构图之前，自己拼一次：\n\n1. **顺序问题**：注意力本身对输入顺序完全无感（打乱序列，输出跟着打乱）——要让它做语言模型，缺什么？你会怎么补？\n2. 自注意力：5.1 的查询来自解码器、键值来自编码器。如果只有一个序列（语言模型没有第二个序列），查询、键、值从哪来？\n3. 因果性：语言模型预测第 $t$ 个词时不能偷看未来——注意力里怎么实现\"只许回头看\"？\n4. 深度的稳定：把六层注意力堆起来，你会复用什么 3.2 的零件？\n\n四问答完，把你拼出的架构画在纸上——再与正文对照。差多少不重要，**每一处差异都是一块值得咀嚼的设计决策**。\n:::\n\n## 核心思想\n\n**自注意力**：查询、键、值全部由同一序列的线性变换生成——\n\n$$\\mathrm{Attention}(Q, K, V) = \\mathrm{softmax}\\.\\left(\\frac{QK^\\top}{\\sqrt{d_k}}\\right)V$$\n\n每个位置向所有位置发问（\"谁和我有关\"），按相关度收集信息。除以 $\\sqrt{d_k}$ 是因为内积的方差随维度增长——不缩放的话 softmax 会过早饱和、梯度消失（2.2 的病以新面目重现）。**注意 $T\\times T$ 的注意力矩阵：每个位置对每个位置**——这就是 O(长度²) 账单的正式签署。\n\n**因果掩码**：把注意力矩阵的上三角（未来位置）置为 $-\\infty$，softmax 后权重为零——\"只许回头看\"用一次掩码乘法解决，没有任何架构改动（对照 5.4：去掉掩码就是 BERT 的双向）。\n\n**位置编码**：给每个位置加一个固定的正弦向量（或学习向量）。注意力的\"无序性\"被这个注入的顺序信息补全。内容与位置的分离——注意力管\"看谁\"，位置编码管\"在哪\"——是此后一切位置方案（可学习、相对位置、RoPE）的共同出发点。\n\n**块的结构**（GPT-2 风格的 pre-LN）：\n\n$$x = x + \\mathrm{MHA}(\\mathrm{LN}(x)); \\qquad x = x + \\mathrm{MLP}(\\mathrm{LN}(x))$$\n\n每一件都似曾相识：残差是 3.2 的（给梯度修高速路）、LN 是 2.3 的（钉住分布）、MLP 是逐位置的非线性。**Transformer 没有发明任何一个新零件——它是一个用注意力做粘合剂的重组装**。研究史在此展现了另一种创新模式：不是发明新积木，而是发现旧积木的正确组合。\n\n## 从零实现\n\n`dlbook.transformer` 提供全部零件（约三百行，`layers.py` 的反向传播值得逐行对读——1.3 的三条递推穿过了 softmax、多头变形与残差）。我们的 `MiniGPT`：2 个块、32 维、2 头、正弦位置编码。上老战场：\n\n::: {#9c96838d .cell execution_count=1}\n``` {.python .cell-code}\nimport time\n\nimport numpy as np\n\nfrom dlbook.data.corpus import char_corpus\nfrom dlbook.transformer import MiniGPT\nfrom dlbook.utils import plot_loss_curves, set_seed\n\nset_seed(42)\n\nids, vocab, inv = char_corpus()\nV = len(vocab)\narr = np.array(ids)\nprint(f\"战绩回顾：均匀 3.30 | 3-gram 计数 1.95 | RNN 2.23 | LSTM 2.83\")\n\nmodel = MiniGPT(V, d_model=32, n_heads=2, n_blocks=2, block_size=64, seed=0)\nprint(f\"MiniGPT 参数量: {model.n_params()}\")\n\nrng = np.random.default_rng(0)\nhistory = []\nt0 = time.time()\nfor step in range(1000):\n    starts = rng.integers(0, len(arr) - 65, size=8)\n    batch = np.stack([arr[s : s + 65] for s in starts])\n    history.append(model.loss_and_backward(batch))\n    model.step(0.15, clip=1.0)  # 梯度裁剪——稳定性的关键配菜\nprint(f\"1000 步用时 {time.time()-t0:.0f}s；最终 loss {history[-1]:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n战绩回顾：均匀 3.30 | 3-gram 计数 1.95 | RNN 2.23 | LSTM 2.83\nMiniGPT 参数量: 27163\n1000 步用时 9s；最终 loss 1.7903\n```\n:::\n:::\n\n\n::: {#1dbfd9c8 .cell execution_count=2}\n``` {.python .cell-code}\nplot_loss_curves({\"MiniGPT char-LM\": history}, title=\"Attention is all you need (for 2.4KB of text)\");\n```\n\n::: {.cell-output .cell-output-display}\n![](part5-transformer_files/figure-html/cell-3-output-1.png){width=565 height=374}\n:::\n:::\n\n\n**1.79**——同一语料的总冠军（超过 3-gram 的 1.95 与 RNN 的 2.23，且收敛快得多）。看它写出的文本：\n\n::: {#0d31004a .cell execution_count=3}\n``` {.python .cell-code}\nout = model.generate([vocab[c] for c in \"the cat \"], n_new=140, temperature=0.7, seed=3)\nprint(\"\".join(inv[i] for i in out))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nthe cat cat bip the pips sma wand smat caverermat smats the s the s frky. thin. the billd sky d the seree s s. s s thetheas smelllllle m s s bonigar\n```\n:::\n:::\n\n\n典型样貌：比 RNN 的采样更像\"英语\"——词的边界干净、常见搭配成串（the/sat/and）、偶尔冒出语料的词组。**同预算下表示质量的差距是肉眼可见的**。\n\n**注意力图：模型在看什么？** 取第一块的平均注意力（一次前向后自动缓存）：\n\n::: {#d83eff32 .cell execution_count=4}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nwindow = np.array(arr[100:132])[None, :]\nmodel.forward(window)\nA = model.blocks[0].attn_map  # (T, T)，头平均\n\nplt.figure(figsize=(4.5, 4))\nplt.imshow(A, cmap=\"viridis\")\nplt.xlabel(\"key position (looked at)\")\nplt.ylabel(\"query position (looking)\")\nplt.title(\"Average attention (block 1): local + sparse long-range\")\nplt.colorbar()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](part5-transformer_files/figure-html/cell-5-output-1.png){width=454 height=348}\n:::\n:::\n\n\n典型的图案：**强对角线（看自己与邻居）+ 零星的长程亮点**。因果掩罩使上三角全黑；对角带是字符 LM 的局部统计；远处亮点是它学到的选择性回看——5.1 对齐热图的直系亲戚。\n\n## 消融实验\n\n**位置编码：注意力的隐形地基。** 把位置编码置零，同预算重训：\n\n::: {#bf6a8b42 .cell execution_count=5}\n``` {.python .cell-code}\nmodel_nopos = MiniGPT(V, d_model=32, n_heads=2, n_blocks=2, block_size=64, seed=0)\nmodel_nopos.pos = np.zeros_like(model_nopos.pos)\nrng = np.random.default_rng(0)\nl_nopos = None\nfor step in range(1000):\n    starts = rng.integers(0, len(arr) - 65, size=8)\n    batch = np.stack([arr[s : s + 65] for s in starts])\n    l_nopos = model_nopos.loss_and_backward(batch)\n    model_nopos.step(0.15, clip=1.0)\nprint(f\"有位置: {history[-1]:.4f} | 无位置: {l_nopos:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n有位置: 1.7903 | 无位置: 4.4949\n```\n:::\n:::\n\n\n**1.79 → 4.49**——没有位置信息，模型甚至差于均匀基线（3.30）：字符袋的歧义比没有信息更糟（\"有 t、h、e、空格……下一个字符是啥？\"）。这个戏剧性的消融说明：注意力的全部序列能力都骑在位置编码上——一个加法注入的、看似不起眼的组件。它也是今天长上下文研究的核心战场（RoPE 的缩放定律、8.x）。\n\n## 本章 Loss 账本\n\n| 问题 | 回答 |\n|---|---|\n| 在优化什么 loss？ | 下一字符交叉熵（与 Part 4 完全相同）——**变的全部是函数族**：从递推到注意力 |\n| 数据从哪来？ | 还是那条 2.4K 语料；历史上它对数据的胃口在下一部分才真正张开 |\n| 买到了什么能力？ | 同预算最低 loss（1.79）；完全并行的前向（下一章的经济学）；可堆叠（残差+LN 的深栈） |\n| 没买到什么？ | O(T²) 的计算与显存；推理仍是自回归串行（生成一步等一步）；本章尺度下采样仍有明显胡话——一切要等规模（Part 6） |\n\n::: {.callout-echo title=\"回声\"}\n- 自注意力 → 今天 LLM 的定义性组件；多头 → 多视角处理的通用术（多模态的跨模态注意力是它的直系后代）；\n- 因果掩码 → 一个布尔矩阵决定\"生成器\"与\"理解器\"的身份（下一章 GPT/BERT 分野的全部技术含量）；\n- 位置编码 → RoPE/ALiBi 与长上下文的军备竞赛（8.x）——**\"内容与位置分离\"的契约至今没有变更**；\n- √d 缩放 → \"维度方差管理\"的常识化——同样的思考出现在一切高维内积场景（对比学习的温度、6.x）；\n- 梯度裁剪 → 训练稳定性的标准配菜——从 LSTM 时代（4.2）传到 Transformer 时代，从未离场。\n:::\n\n::: {.callout-paper title=\"论文时光机\"}\n**Vaswani, A. et al. (2017).** *Attention is all you need.* NeurIPS 2017.\n\n- **读什么**：表 1（架构超参——注意 d_model=512、8 头、6 层，以及\"为什么这样配\"只给了半页直觉）；图 2（多头与缩放点积注意力的原图——本章实现的对照版）；\n- 跳过：label smoothing 等训练细节（但记得它们存在——本章我们的 `clip=1.0` 就是向这些细节致敬）；\n- 历史注：作者们事后回忆，标题是组内争论后的挑衅式定稿。配套读 Kaplan et al. (2020)——三年后同一架构在 1750 亿参数上的续集：架构论文与规模论文是同一部戏剧的两幕。\n:::\n\n## 遗留问题\n\n1. Transformer 真正的杀手锏到底是什么——是精度还是**可并行带来的训练经济学**？（→ 下一章：用墙钟时间核算）；\n2. 因果掩罩去掉会怎样？生成与理解的两条路线如何分野？（→ 5.4 GPT vs BERT）；\n3. 这个架构吞下更多数据与参数时会发生什么？（→ Part 6：scaling laws——loss 的可预测时代）。\n\n## 参考文献\n\n1. Vaswani et al. (2017). *Attention Is All You Need*. *NeurIPS*. [↗ 搜索原文](https://scholar.google.com/scholar?q=al.%202017%20Attention%20Is%20All%20You%20Need)\n2. Kaplan et al. (2020). *Scaling Laws for Neural Language Models*. *arXiv preprint arXiv:2001.08361*. [↗ 搜索原文](https://scholar.google.com/scholar?q=al.%202020%20Scaling%20Laws%20for%20Neural%20Language%20Models)\n\n\n## 练习\n\n1. **造轮子**：遮住 `MultiHeadAttention.backward`，从 softmax 雅可比与多头变形重写；再用有限差分穿透整网对拍（`tests/test_transformer.py` 有现成裁判）。\n2. 预测再运行：把头数从 2 改到 8（d_model 不变，每头更小），loss 与注意力图各怎么变？（提示：子空间更窄、视角更多。）\n3. 消融：把 √d 缩放去掉（`S = QK^T` 不除），重训——2.2 的病以什么面目回来？（观察 loss 曲线的早期形态与最终值。）\n4. 论文映射：用四问账本拆 Vaswani 2017——特别核对\"没买到\"一栏：O(T²) 与自回归串行这两张账单，当时论文提了吗？\n5. 进阶：实现学习式位置嵌入（随机初始化、随训练更新），与正弦版对照；再把它外推到 block_size 之外（位置 65+）看崩坏——这是 RoPE 们要解决的问题。\n\n::: {.callout-note title=\"练习答案\" collapse=\"true\"}\n**练习 2**：loss 基本持平或略变（容量重组而非扩容）；注意力图显著更分化（每头专精不同模式——多头的意义在图上比在 loss 上明显）。\n\n**练习 3**：早期 loss 下降更快（更大的有效步长）然后更早陷入平台且最终值更差——饱和的 softmax 把注意力锁死在初期模式上（\"过旱承诺\"）。√d 不是数值美容，是优化通道的守门员。\n\n**练习 5 提示**：学习式嵌入在 block_size 内更好（容量更大），超出即崩（没有 65+ 的训练信号）。正弦版的\"外推性\"在原论文是宣称、后续研究发现也有条件——架构论文里的\"优点\"要当假设对待。\n:::\n\n",
    "supporting": [
      "part5-transformer_files\\figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}