{
  "hash": "646cfb3d5863e73a8954491dba4d72d1",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Chinchilla [@hoffmann2022]：等算力下的再平衡\"\n---\n\n上一章的曲线回答了\"更大更好吗\"，却没有回答一个更贵的问题：**给我一笔固定的算力，该怎么花？** 2020 年的实践答案是\"买参数\"。Kaplan 的曲线读起来像\"大模型优先\"。2022 年，DeepMind 的 Hoffmann 等人（论文代号 Chinchilla）用四百多次受控实验重算了这本账，结论掀了桌子：同等算力下，参数与训练数据应当大致等比例增长（约每参数 20 个 token）。按此配方，700 亿参数的 Chinchilla 打败了它四倍大的 Gopher。行业随即转向\"更小的模型、更多的数据\"。LLaMA [@touvron2023] 一族由此而生。本章在玩具上重演这本账的算法：等算力扫描。\n\n::: {.callout-tip title=\"算力需求\"}\n**B 级**：笔记本 CPU 约 5–6 分钟（四档等算力训练；各档独立可跑）。\n:::\n\n::: {.callout-era title=\"时代快照 · 2022\"}\n- **算力**：训练预算进入亿美元时代；\"训练一次的沉没成本\"让配比错误的代价变得惊人；\n- 数据：高质量文本的获取开始成为瓶颈的先兆（9.2 的数据墙前夜）；\n- 认知：GPT-3 之后行业默认\"参数量 = 排行榜名次\"；Chinchilla 之前已有零星质疑（例如\"训练不足的大模型\"现象），但缺少系统性的再核算；\n- 关键事实：Chinchilla 的四百多个实验点本身比结论更宝贵。它把\"如何做 scaling 实验\"（统一配方、等算力族、三维扫描）变成了方法论模板，此后所有大厂的技术报告都在模仿这个文体。\n:::\n\n## 本章问题\n\n1. **等算力约束**是什么意思，如何在实验里实现？（参数 × 步数 ≈ 常数）\n2. 等算力下扫尺寸，曲线是什么形状？（预期一个 U 型。最优尺寸夹在\"小而充分训练\"与\"大而欠训练\"之间）\n3. 最优点告诉了我们什么？为什么它随算力预算移动？\n\n## 历史中的尝试（包括弯路）\n\n**Kaplan 的读法与偏差**：2020 [@kaplan2020] 年的定律说\"大模型在相同算力下更优\"。但那些测量里的模型大多没有训到收敛，且固定了一批训练细节（学习率日程的长度、临界批次）。在欠训练的世界里比较大模型，会系统性高估\"大\"的边际收益。Chinchilla 的第一刀就砍在这里：统一配方、训到位、再比较。\n\n**三族方法，一个结论**：Hoffmann 等人用三种独立方法（固定模型扫数据、固定数据扫模型、等算力参数化拟合）交叉验证，收敛到同一个配比（每参数约 20 token）。多方法的一致性比单一方法的精度更有说服力。研究方法论的一堂公开课。\n\n**回响**：Gopher（2800 亿参数）被 Chinchilla（700 亿）以相同算力击败；Meta 的 LLaMA（2023）按新配方用\"小\"模型追平大模型，并把权重开源。配比的修正直接催生了开源时代的可行路线（6.4 的剧情）。此外它还改写了推理经济学：训练一次省下的钱之外，小模型的每一次推理都更便宜。部署时代的隐藏红利。\n\n**弯路：把 20 token/参数当物理常数**。后续研究（如对多轮训练、数据复用的再核算）表明这个比率依赖设定；把它当铁律的做法很快被打破。研究结论的适用域与结论本身同样重要。账本栏目的老教导。\n\n*缓一缓。*让我们把刚才的内容用一句话再说一遍。这一节的核心是：历史中的尝试（包括弯路）。\n\n\n::: {.callout-research title=\"停一停，你来当研究者\"}\n设定：预算 $C$ = 27293 × 1200（param-steps，参数量 × 训练步数）。四个候选：\n\n| 尺寸 | 参数 | 可训步数 |\n|---|---|---|\n| d=8 | 2.2K | 14640 |\n| d=16 | 7.5K | 4357 |\n| d=32 | 27K | 1200 |\n| d=64 | 104K | 315 |\n\n**运行之前**：\n\n1. 预测四档的验证 loss 排序（注意上一章的固定步数扫描里 d=64 最好。**这次为什么可能翻车**？）；\n2. 画出你预测的\"loss vs 尺寸\"曲线（横轴对数尺寸）。U 型谷底在哪一档？\n3. 把预算放大 10 倍，谷底往哪边移？为什么？\n\n写完再运行。第 1 问的正确答案会让一部分人大吃一惊。\n:::\n\n## 核心思想\n\n**等算力族（iso-compute family）**：固定 $C \\approx N \\times S$（参数 × 步数），扫描 $N$。每个预算 $C$ 下存在一个计算最优尺寸 $N^*(C)$：比它小，模型容量不足（训练步数浪费在已收敛的模型上）；比它大，步数不够（模型欠训练，参数浪费）。把所有预算的最优点连起来，得到 $N^*(C)$ 的 scaling。这就是 Chinchilla 配比。\n\n**直觉版**：训练像烧砖。参数是窑的容积、数据是柴火。窑太大柴不够，烧出半熟的砖；窑太小柴太多，烧完还剩火。约束不是窑也不是柴，是总热量。\n\n**为什么它推翻了 Kaplan**：两者并不真的矛盾。差别在\"训练到什么程度算数\"。Kaplan 族的比较隐含\"欠训练也算\"，Chinchilla 族要求\"算力花完即止\"。同样的数据、不同的实验协议、不同的结论。读到任何 scaling 主张时，先问它的协议。\n\n**对本书主线的意义**：这是 loss 账本最辉煌的一页。\"如何最便宜地降 loss\"的会计学。研究从\"找到更好的方法\"扩展到\"找到更优的资源配置\"，这门手艺此后统治了工业界的模型训练。\n\n*缓一缓。*把刚才的推导或实验消化一下再继续。这一节的核心是：核心思想。\n\n\n## 从零实现\n\n复用上一章的全部装备，只把扫描协议换成等算力：\n\n::: {#a4cbe361 .cell execution_count=1}\n``` {.python .cell-code}\nimport time\n\nimport numpy as np\n\nfrom dlbook.data.corpus import char_corpus, make_grammar_corpus\nfrom dlbook.transformer import MiniGPT\nfrom dlbook.utils import set_seed\n\nset_seed(42)\n\narr_t = np.array(char_corpus(make_grammar_corpus(60000, seed=0))[0])\narr_v = np.array(char_corpus(make_grammar_corpus(12000, seed=1))[0])\nV = len(char_corpus(make_grammar_corpus(60000, seed=0))[1])  # 词表取自完整训练文本\nvb = np.stack([arr_v[s : s + 65] for s in np.random.default_rng(7).integers(0, len(arr_v) - 65, size=200)])\n\n\ndef train_eval(d_model, steps, seed=0):\n    heads = 2 if d_model <= 32 else 4\n    m = MiniGPT(V, d_model=d_model, n_heads=heads, n_blocks=2, block_size=64, seed=seed)\n    rng = np.random.default_rng(seed)\n    for step in range(steps):\n        lr = 0.15 * min(1.0, (step + 1) / 150) * (1 - 0.9 * step / max(steps, 1))\n        starts = rng.integers(0, len(arr_t) - 65, size=16)\n        batch = np.stack([arr_t[s : s + 65] for s in starts])\n        m.loss_and_backward(batch)\n        m.step(lr, clip=1.0)\n    return m, float(m.loss_on(vb))\n\n\nBUDGET = 27293 * 1200  # param-steps（以 d=32 的上一章配置定锚）\nconfigs = [(8, 2237), (16, 7517), (32, 27293), (64, 103709)]\n\nresults = {}\nfor d, n in configs:\n    steps = int(BUDGET / n)\n    t0 = time.time()\n    m, vl = train_eval(d, steps)\n    results[d] = vl\n    print(f\"d={d:3d} ({n:6d} 参数, {steps:5d} 步): val = {vl:.4f} ({time.time()-t0:.0f}s)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nd=  8 (  2237 参数, 14640 步): val = 1.7329 (205s)\nd= 16 (  7517 参数,  4357 步): val = 1.5540 (65s)\nd= 32 ( 27293 参数,  1200 步): val = 1.8942 (41s)\nd= 64 (103709 参数,   315 步): val = 2.1518 (22s)\n```\n:::\n:::\n\n\n::: {#d6d8da41 .cell execution_count=2}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nds = list(results)\nplt.figure(figsize=(5.5, 4))\nplt.plot(ds, [results[d] for d in ds], \"o-\")\nplt.xscale(\"log\", base=2)\nplt.xlabel(\"model size (d_model, log)\")\nplt.ylabel(\"val loss at fixed compute\")\nplt.title(\"The iso-compute U-curve: too small underfits, too big undertrains\")\nbest = min(results, key=results.get)\nplt.axvline(best, ls=\"--\", c=\"red\", label=f\"compute-optimal: d={best}\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](part6-chinchilla_files/figure-html/cell-3-output-1.png){width=544 height=377}\n:::\n:::\n\n\n典型读数（对照你的预测）：**d=8 → 1.73，d=16 → 1.55（谷底），d=32 → 1.89，d=64 → 2.15**。清晰的 U 型。三个教训当场兑现：\n\n- **上一章的冠军（d=64）在本协议下垫底**：315 步远不够喂饱十万个参数。\"更大更好\"是\"步数富余\"世界里的结论；\n- 谷底在 d=16：等算力下，中等身材 + 充分训练胜过巨人 + 浅尝辄止；\n- 有趣的细节：d=8（步数超多）拿到 1.73，好于 d=32/64。小模型充分训练的顽强，正是 LLaMA 路线的玩具版。\n\n**玩具与现实的换算**：真实 Chinchilla 配比约 20 token/参数。我们的谷底 d=16：训练 4357 步 × 每步 1024 token ≈ 4.5M token 对 7.5K 参数。比率约 600，远大于 20。原因正是上一章的那堵墙：六万字符的语料让大模型无利可图，把最优点狠狠推向小模型。最优配比是（算力、数据供给）的函数。数据稀缺的世界里，\"小而精\"永远正确；数据充沛的世界里，配比才由算力单方面决定。我们的玩具恰好站在\"数据稀缺世界\"，与 2024 年后的人类殊途同归（9.2 的伏笔，以想不到的方式提前）。\n\n*缓一缓。*回顾一下这一节讲了什么。这一节的核心是：从零实现。\n\n\n## 消融实验\n\n**预算加倍，谷底去哪？** 把 BUDGET ×2，重扫（每档步数加倍）。观察谷底是否右移、以及右移多少：\n\n::: {#096b2021 .cell execution_count=3}\n``` {.python .cell-code}\nBUDGET2 = BUDGET * 2\nresults2 = {}\nfor d, n in configs:\n    steps = int(BUDGET2 / n)\n    m, vl = train_eval(d, steps)\n    results2[d] = vl\n    print(f\"预算x2 d={d:3d} ({steps:5d} 步): val = {vl:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n预算x2 d=  8 (29281 步): val = 4.2507\n预算x2 d= 16 ( 8714 步): val = 0.9220\n预算x2 d= 32 ( 2400 步): val = 1.6907\n预算x2 d= 64 (  631 步): val = 2.3347\n```\n:::\n:::\n\n\n典型结果：谷底向右移动一档（更多算力买得起更大的\"充分训练\"模型），但是，受数据墙牵引，移动幅度有限。**$N^*(C)$ 的轨迹 = 算力推着走、数据墙拦着走**。两股力的合力方向，就是 6.4 与 9.2 要继续展开的产业剧情。\n\n*缓一缓。*到这里停一停，把刚走过的路理一理。这一节的核心是：消融实验。\n\n\n## 本章 Loss 账本\n\n| 问题 | 回答 |\n|---|---|\n| 在优化什么 loss？ | 同一条 loss。本章优化的是**它的单价**：每 FLOP 买多少改善 |\n| 数据从哪来？ | 同上；但数据量首次作为约束变量进入优化问题（配比的另一半） |\n| 买到了什么能力？ | 资源配置的会计学：等算力 U 曲线、计算最优尺寸、训练前的预算规划 |\n| 没买到什么？ | 配比的普适性（依赖配方与数据供给）；推理成本的全貌（训练省了，推理呢？→ 下一章 MoE 的动因之一） |\n\n::: {.callout-echo title=\"回声\"}\n- 等算力思维 → 今天一切\"训练预算 vs 模型规模\"的决策框架；推测解码、量化等推理经济学是它的镜像课题；\n- LLaMA 路线 → \"足够小的充分训练模型 + 开源\"。6.4 与开源时代的直接伏笔；\n- 实验协议决定结论 → 读一切 benchmark 论文的第一课（6.3 的度量批判是其孪生）；\n- 数据墙前的配比漂移 → 合成数据与数据复用的经济学（9.2）。\n:::\n\n::: {.callout-paper title=\"论文时光机\"}\n**Hoffmann, J. et al. (2022).** *Training compute-optimal large language models.* arXiv:2203.15556.（Chinchilla）\n\n- **读什么**：图 2（等算力族与最优前沿的三联图。本章 U 曲线的原版）与第 4 节（三种方法的交叉验证）；\n- 跳过：硬件细节；\n- 历史注：配套读 Kaplan et al. (2020) 并亲手找出两文协议的差异（收敛标准、日程长度、批次策略）。这是比读结论本身更好的训练。再读 Touvron et al. (2023) 的 LLaMA 论文第一节的动机段：它把 Chinchilla 的修正翻译成了开源战略。\n:::\n\n## 遗留问题\n\n1. 等算力的谷底给了\"最好的平均 loss\"。但 loss 平滑改善时，下游能力也平滑吗？（→ 下一章：涌现之争）；\n2. \"参数太多浪费、数据太多也浪费\"。有没有办法**解耦参数与算力**？（→ 6.4：MoE，以及更远的稀疏化家族）。\n\n*缓一缓。*让我们把刚才的内容用一句话再说一遍。这一节的核心是：遗留问题。\n\n\n## 参考文献\n\n1. Hoffmann et al. (2022). *Training Compute-Optimal Large Language Models*. *arXiv preprint arXiv:2203.15556*. [↗ 搜索原文](https://scholar.google.com/scholar?q=al.%202022%20Training%20Compute-Optimal%20Large%20Language%20Models)\n2. Kaplan et al. (2020). *Scaling Laws for Neural Language Models*. *arXiv preprint arXiv:2001.08361*. [↗ 搜索原文](https://scholar.google.com/scholar?q=al.%202020%20Scaling%20Laws%20for%20Neural%20Language%20Models)\n3. Touvron et al. (2023). *LLaMA*. *arXiv preprint arXiv:2302.13971*. [↗ 搜索原文](https://scholar.google.com/scholar?q=al.%202023%20LLaMA)\n\n\n## 练习\n\n1. **造轮子**：实现三维网格的迷你版（3 尺寸 × 3 步数，等量九点），画出等 loss 等高线图。$N^*(C)$ 从等高线的切点上读出来。\n2. 预测再运行：把语料换成 12 万字符（数据墙外推），谷底往哪移？先按\"两股力\"的框架预测，再验证。\n3. 消融：等算力扫描里把学习率日程的 warmup 拿掉（小步数档几乎没有 warmup 余地），谷底移动吗？。短训练的配方与长训练不同，这正是 Chinchilla 方法论中最容易被忽视的细节。\n4. 论文映射：用四问账本（+算力账本）拆 Chinchilla。注意它\"买到\"的是决策规则而非能力，这类论文的价值如何在学术评价体系里被低估又如何被工业界兑现？\n5. 进阶：给我们的玩具算\"token/参数\"配比曲线（对每个预算档算 $C/N^*$），观察它随预算的变化方向，与真实世界 20 token/参数 的来源（数据充足假设）对照。\n\n::: {.callout-note title=\"练习答案\" collapse=\"true\"}\n**练习 2**：谷底右移（数据墙退远，算力独大）。移动幅度取决于新增数据的质量；若只是把旧语料复制一遍，墙不动（信息量未增）。\n\n**练习 3**：小步数档受 warmup 影响最大（预算的相当比例花在暖机上）。拿掉 warmup 后短训练反而更高效，谷底左移。配比结论对配方细节敏感，所以，论文复现比想象中难。\n\n**练习 5 提示**：玩具的配比随预算上升（数据墙约束松了）；真实世界在数据充足段的渐近值约 20。把两条线画在同一张图上，\"研究结论的适用域\"就有了几何形状。\n:::\n\n",
    "supporting": [
      "part6-chinchilla_files\\figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}